project_name: terraform-provider-validatefx

before:
  hooks:
    - go test ./...

builds:
  - id: terraform-provider
    main: ./main.go
    binary: terraform-provider-validatefx_v{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: terraform-provider
    builds:
      - terraform-provider
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

changelog:
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
